<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ContinuousIntegrationBuild Condition="'$(GITHUB_ACTIONS)' == 'true'">true</ContinuousIntegrationBuild>
    <TreatWarningsAsErrors Condition="'$(ContinuousIntegrationBuild)' == 'true'">true</TreatWarningsAsErrors>
    <TreatWarningsAsErrors Condition="'$(ContinuousIntegrationBuild)' != 'true'">false</TreatWarningsAsErrors>
    <LangVersion>14.0</LangVersion>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <VersionPrefix Condition="'$(VersionPrefix)' == ''">1.1.0</VersionPrefix>
    <Version Condition="'$(Version)' == '' and '$(VersionSuffix)' != ''">$(VersionPrefix)-$(VersionSuffix)</Version>
    <Version Condition="'$(Version)' == ''">$(VersionPrefix)</Version>
    <AssemblyVersion Condition="'$(AssemblyVersion)' == ''">1.1.0.0</AssemblyVersion>
    <FileVersion Condition="'$(FileVersion)' == ''">1.1.0.0</FileVersion>
    <InformationalVersion Condition="'$(InformationalVersion)' == ''">$(Version)</InformationalVersion>
  </PropertyGroup>
</Project>
